# Generated by Django 3.2.5 on 2021-07-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador', models.CharField(max_length=150, verbose_name='Comprador')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('preco', models.IntegerField(max_length=10, verbose_name='Preço')),
                ('quantidade', models.IntegerField(max_length=10, verbose_name='Quantidade')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('fornecedor', models.CharField(max_length=150, verbose_name='Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
